// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package account

import mock "github.com/stretchr/testify/mock"

// MockAccountRepository is an autogenerated mock type for the AccountRepository type
type MockAccountRepository struct {
	mock.Mock
}

// LoadAccount provides a mock function with given fields: id
func (_m *MockAccountRepository) LoadAccount(id string) (*Account, error) {
	ret := _m.Called(id)

	var r0 *Account
	if rf, ok := ret.Get(0).(func(string) *Account); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Account)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveAccount provides a mock function with given fields: account
func (_m *MockAccountRepository) SaveAccount(account Account) (*Account, error) {
	ret := _m.Called(account)

	var r0 *Account
	if rf, ok := ret.Get(0).(func(Account) *Account); ok {
		r0 = rf(account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Account)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(Account) error); ok {
		r1 = rf(account)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
