// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package operation

import mock "github.com/stretchr/testify/mock"

// MockOperationTypeRepository is an autogenerated mock type for the OperationTypeRepository type
type MockOperationTypeRepository struct {
	mock.Mock
}

// LoadOperation provides a mock function with given fields: id
func (_m *MockOperationTypeRepository) LoadOperation(id int) (*OperationType, error) {
	ret := _m.Called(id)

	var r0 *OperationType
	if rf, ok := ret.Get(0).(func(int) *OperationType); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*OperationType)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveOperation provides a mock function with given fields: operationModel
func (_m *MockOperationTypeRepository) SaveOperation(operationModel OperationType) (*OperationType, error) {
	ret := _m.Called(operationModel)

	var r0 *OperationType
	if rf, ok := ret.Get(0).(func(OperationType) *OperationType); ok {
		r0 = rf(operationModel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*OperationType)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(OperationType) error); ok {
		r1 = rf(operationModel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
