// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package db

import (
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// MockDatabaseManager is an autogenerated mock type for the DatabaseManager type
type MockDatabaseManager struct {
	mock.Mock
}

// GetDatabaseConnection provides a mock function with given fields:
func (_m *MockDatabaseManager) GetDatabaseConnection() (*gorm.DB, error) {
	ret := _m.Called()

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Migrate provides a mock function with given fields: model
func (_m *MockDatabaseManager) Migrate(model interface{}) error {
	ret := _m.Called(model)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
